source 'https://github.com/CocoaPods/Specs.git'

target 'NibView', :exclusive => true do
  pod "NibView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NibView", :path => "../"

  
end
